import {PrismaClient, Prisma} from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // User
  await prisma.user.createMany({
    data: [
      {
        externalUserId: '1',
        firstName: 'Mansoor',
        lastName: 'Siddeeq',
        email: 'mansoor.siddeeq@formidable.com',
        gender: 'MALE',
        preferredPosition: 'STRIKER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: true,
        userType: 'ADMIN',
      },
      {
        externalUserId: '2',
        firstName: 'Alejandro',
        lastName: 'Butrón Pérez',
        email: 'alejandro.butron@formidable.com',
        gender: 'MALE',
        preferredPosition: 'STRIKER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: true,
        userType: 'ADMIN',
      },
      {
        externalUserId: '3',
        firstName: 'Luis',
        lastName: 'Abarca',
        email: 'luis.abarca@formidable.com',
        gender: 'MALE',
        preferredPosition: 'STRIKER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: true,
        userType: 'ADMIN',
      },
      {
        externalUserId: '4',
        firstName: 'Giorgos',
        lastName: 'Giakoumakis',
        email: 'giakoumakis@domain.com',
        gender: 'MALE',
        preferredPosition: 'STRIKER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: true,
        userType: 'CAPTAIN',
      },
      {
        externalUserId: '5',
        firstName: 'Thiago',
        lastName: 'Almada',
        email: 'almada@domain.com',
        gender: 'MALE',
        preferredPosition: 'MIDFIELDER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '6',
        firstName: 'Luiz',
        lastName: 'Araújo',
        email: 'araujo@domain.com',
        gender: 'MALE',
        preferredPosition: 'WINGER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '7',
        firstName: 'Caleb',
        lastName: 'Wiley',
        email: 'wiley@domain.com',
        gender: 'MALE',
        preferredPosition: 'DEFENDER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '8',
        firstName: 'Andrew',
        lastName: 'Gutman',
        email: 'gutman@domain.com',
        gender: 'MALE',
        preferredPosition: 'DEFENDER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '9',
        firstName: 'Tyler',
        lastName: 'Wolff',
        email: 'wolff@domain.com',
        gender: 'MALE',
        preferredPosition: 'WINGER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '10',
        firstName: 'Machop',
        lastName: 'Chol',
        email: 'chol@domain.com',
        gender: 'MALE',
        preferredPosition: 'MIDFIELDER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '11',
        firstName: 'Brooks',
        lastName: 'Lennon',
        email: 'lennon@domain.com',
        gender: 'MALE',
        preferredPosition: 'DEFENDER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '12',
        firstName: 'Matheus',
        lastName: 'Rossetto',
        email: 'rossetto@domain.com',
        gender: 'MALE',
        preferredPosition: 'MIDFIELDER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '13',
        firstName: 'Juan José',
        lastName: 'Sánchez Purata',
        email: 'purata@domain.com',
        gender: 'MALE',
        preferredPosition: 'DEFENDER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '14',
        firstName: 'Luis',
        lastName: 'Abram',
        email: 'abram@domain.com',
        gender: 'MALE',
        preferredPosition: 'DEFENDER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '15',
        firstName: 'Osvaldo',
        lastName: 'Alonso',
        email: 'alonso@domain.com',
        gender: 'MALE',
        preferredPosition: 'MIDFIELDER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '16',
        firstName: 'Miguel',
        lastName: 'Berry',
        email: 'berry@domain.com',
        gender: 'MALE',
        preferredPosition: 'STRIKER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '17',
        firstName: 'Clément',
        lastName: 'Diop',
        email: 'diop@domain.com',
        gender: 'MALE',
        preferredPosition: 'GOALIE',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '18',
        firstName: 'Brad',
        lastName: 'Guzan',
        email: 'guzan@domain.com',
        gender: 'MALE',
        preferredPosition: 'GOALIE',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '19',
        firstName: 'Charlie',
        lastName: 'Asensio',
        email: 'asensio@domain.com',
        gender: 'MALE',
        preferredPosition: 'DEFENDER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '20',
        firstName: 'Matt',
        lastName: 'Bersano',
        email: 'bersano@domain.com',
        gender: 'MALE',
        preferredPosition: 'GOALIE',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '21',
        firstName: 'Will',
        lastName: 'Bruin',
        email: 'bruin@domain.com',
        gender: 'MALE',
        preferredPosition: 'STRIKER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '22',
        firstName: 'Julio',
        lastName: 'Cascante',
        email: 'cascante@domain.com',
        gender: 'MALE',
        preferredPosition: 'DEFENDER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '23',
        firstName: 'Sofiane',
        lastName: 'Djeffal',
        email: 'djeffal@domain.com',
        gender: 'MALE',
        preferredPosition: 'MIDFIELDER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '24',
        firstName: 'Moussa',
        lastName: 'Djitté',
        email: 'djitte@domain.com',
        gender: 'MALE',
        preferredPosition: 'STRIKER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '25',
        firstName: 'Sebastián',
        lastName: 'Driussi',
        email: 'driussi@domain.com',
        gender: 'MALE',
        preferredPosition: 'STRIKER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '26',
        firstName: 'Diego',
        lastName: 'Fagundez',
        email: 'fagundez@domain.com',
        gender: 'MALE',
        preferredPosition: 'MIDFIELDER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '27',
        firstName: 'Ethan',
        lastName: 'Finlay',
        email: 'finlay@domain.com',
        gender: 'MALE',
        preferredPosition: 'MIDFIELDER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: true,
        userType: 'CAPTAIN',
      },
      {
        externalUserId: '28',
        firstName: 'Calvin Jay',
        lastName: 'Fodrey',
        email: 'fodrey@domain.com',
        gender: 'MALE',
        preferredPosition: 'MIDFIELDER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '29',
        firstName: 'Jon',
        lastName: 'Gallagher',
        email: 'gallagher@domain.com',
        gender: 'MALE',
        preferredPosition: 'DEFENDER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '30',
        firstName: 'Hector',
        lastName: 'Jimenez',
        email: 'jimenez@domain.com',
        gender: 'MALE',
        preferredPosition: 'DEFENDER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '31',
        firstName: 'Kipp',
        lastName: 'Keller',
        email: 'keller@domain.com',
        gender: 'MALE',
        preferredPosition: 'DEFENDER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '32',
        firstName: 'Zan',
        lastName: 'Kolmanic',
        email: 'kolmanic@domain.com',
        gender: 'MALE',
        preferredPosition: 'DEFENDER',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
      {
        externalUserId: '33',
        firstName: 'Damian',
        lastName: 'Las',
        email: 'las@domain.com',
        gender: 'MALE',
        preferredPosition: 'GOALIE',
        skillLevel: 'ADVANCED',
        status: 'JOINED',
        captainInterest: false,
        userType: 'PLAYER',
      },
    ],
  });

  // League
  await prisma.league.createMany({
    data: [
      {
        id: 1,
        name: 'MLS Preseason',
        description: '2023 Major League Soccer preseason',
        season: 'Preseason',
        startDate: new Date(2023, 1, 1, 0, 0, 1),
        endDate: new Date(2023, 2, 24, 23, 59, 59),
        status: 'INACTIVE',
        createdById: 1,
      },
      {
        id: 2,
        name: 'MLS Regular Season',
        description: '2023 Major League Soccer season',
        season: 'Regular Season',
        startDate: new Date(2023, 2, 25, 0, 0, 1),
        endDate: new Date(2023, 10, 21, 23, 59, 59),
        status: 'ACTIVE',
        createdById: 1,
      },
    ],
  });

  // Team
  await prisma.team.createMany({
    data: [
      {
        id: 1,
        leagueId: 2,
        name: 'Atlanta United',
        captainId: 4,
        feeStatus: 'PAID',
        division: 'D1',
        wins: 6,
        losses: 4,
        draws: 5,
        createdById: 1,
      },
      {
        id: 2,
        leagueId: 2,
        name: 'Austin FC',
        captainId: 27,
        feeStatus: 'PAID',
        division: 'D1',
        wins: 4,
        losses: 6,
        draws: 4,
        createdById: 1,
      },
    ],
  });

  // Game
  await prisma.game.create({
    data: {
      id: 1,
      leagueId: 2,
      homeTeamId: 1,
      awayTeamId: 2,
      homeTeamScore: 2,
      awayTeamScore: 1,
      gameResult: 'HOME_WIN',
      isForfeit: false,
      createdById: 1,
    },
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
    console.log('Seed completed');
  })
  .catch(async e => {
    console.log(e);
    await prisma.$disconnect();
    process.exit();
  });
