-- AlterTable
ALTER TABLE "User" ALTER COLUMN "createdAt" DROP DEFAULT,
ALTER COLUMN "createdAt" SET DATA TYPE TEXT,
ALTER COLUMN "modifiedAt" SET DATA TYPE TEXT,
ALTER COLUMN "createdBy" DROP NOT NULL,
ALTER COLUMN "modifiedBy" DROP NOT NULL,
ALTER COLUMN "birthDate" DROP NOT NULL,
ALTER COLUMN "birthDate" SET DATA TYPE TEXT;
