import Head from 'next/head';
// import Image from 'next/image';
import {Inter} from 'next/font/google';
import styles from '@/styles/Home.module.css';
import {useUser} from '@auth0/nextjs-auth0/client';
import {Button} from '@nextui-org/react';

const inter = Inter({subsets: ['latin']});

export default function Home() {
  const {user} = useUser();

  return (
    <>
      <Head>
        <title>Soccer Manager - NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          {user ? (
            <>
              <p>Welcome, {user.nickname ?? 'Default User'}!</p>
              <Button>Click me</Button>
            </>
          ) : (
            <p>Please login via the link above.</p>
          )}
        </div>
      </main>
    </>
  );
}
